# MySQL.  Versions 4.1 and 5.0 are recommended. aws 5.5.17
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  database: tbd_store23_development
  pool: 5
  username: tbdstore23user
  password: tbdstore23pass
  socket: /var/run/mysqld/mysqld.sock